dataset: test_causal
output_dir: '.'
z_dims: [1,1,1,4]
v_dim: 10
x_min: 0
x_max: 3
sigma_v: 0.5
sigma_x: 0.5
sigma_y: 0.5
lr_theta: 0.005
lr_z: 0.005
g_units: [64,64,64,64,64]
e_units: [64,64,64,64,64]
f_units: [64,32,8]
h_units: [64,32,8]
save_res: True
save_model: False
binary_treatment: False